---.
- name: recargar reglas de auditd
  ansible.builtin.command:
    cmd: augenrules --load
  changed_when: true

- name: reiniciar auditd
  ansible.builtin.command:
    cmd: service auditd restart
  changed_when: true

- name: actualizar grub
  ansible.builtin.command:
    cmd: "{{ auditd_grub_update_cmd }}"
  changed_when: true
