---
# =============================================================
#  Hardening base
# =============================================================

- name: Endurecimiento base de la infraestructura
  hosts: all
  become: true
  force_handlers: true

  roles:
    - role: base
      tags: [base]

    - role: firewall_nftables
      tags: [firewall]

    # Pendiente
    # - role: ssh_hardening
    #   tags: [ssh]
    # - role: auditd
    #   tags: [auditoria]
    # - role: hardening_cis
    #   tags: [cis]
