---
# =============================================================
#  Hardening base
# =============================================================

- name: Endurecimiento base de la infraestructura
  hosts: all
  become: true

  roles:
    - role: base
      tags: [base]

    # Pendientes:
    # - role: firewall_nftables
    #   tags: [firewall]
    # - role: ssh_hardening
    #   tags: [ssh]
    # - role: auditd
    #   tags: [auditoria]
    # - role: hardening_cis
    #   tags: [cis]
