---
# =============================================================
#  Playbook para hardening
# =============================================================

- name: Endurecimiento base de la infraestructura
  hosts: all
  become: true
  force_handlers: true

  roles:
    - role: base
      tags: [base]

    - role: firewall_nftables
      tags: [firewall]

    - role: ssh_hardening
      tags: [ssh]

    - role: auditd
      tags: [auditoria]

    - role: sysctl_hardening
      tags: [sysctl]

    - role: password_policy
      tags: [contrasenas]
