---
# handler al finalizar el play ante notificacion de alguna tarea
# evita reiniciar el servicio

- name: reiniciar chrony
  ansible.builtin.service:
    name: "{{ base_chrony_service }}"
    state: restarted

- name: recargar systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
