---
auditd_paquetes:
  - audit
auditd_grub_update_cmd: "grubby --update-kernel=ALL --args='audit=1 audit_backlog_limit={{ auditd_backlog_limit }}'"
auditd_conf_firewall: "/etc/sysconfig/nftables.conf"
auditd_dir_sshd_extra: "/etc/ssh/sshd_config.d"
auditd_conf_chrony: "/etc/chrony.conf"
